apiVersion: v1
kind: Service
metadata:
  name: logging-service
spec:
  selector:
    app: logging
  ports:
    - port: 5001
      protocol: TCP      
      targetPort: 5001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: tenant-service
spec:
  selector:
    app: tenant
  ports:
    - port: 5002
      protocol: TCP
      targetPort: 5002
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post
  ports:
    - port: 5003
      protocol: TCP      
      targetPort: 5003
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: "TCP"
      port: 4200
      targetPort: 4200            
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: admin-frontend-service
spec:
  selector:
    app: admin-frontend
  ports:
    - protocol: "TCP"
      port: 4300
      targetPort: 4200            
  type: LoadBalancer    